name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["testing-issues"]
assignees:
  - aputtu
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! Please, add screenshots and instructions for how to reproduce, if possible.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which type of operating system is affected by the issue?
      options:
        - Windows
        - MacOS
        - Linux
        - Multiple types
    validations:
      required: false
  - type: dropdown
    id: network_protocol
    attributes:
      label: Which network protocol were you using?
      description: If possible, please inform us on the communication protocol. 
      multiple: true
      options:
        - HTTP(S)
        - SFTP
        - WebDAV
        - RSYNC
        - FTP(S)
        - Multiple
        - I don't know
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: By submitting this issue, you agree to contributing to software under the terms stated in the [GPL-2.0 license](https://github.com/ucphhpc/migrid-sync?tab=GPL-2.0-1-ov-file#readme) the project's [Terms of Use](https://dk-www.migrid.org/public/terms.html). 
      options:
        - label: I accept to the project's Terms of Use and its License
          required: true
